namedict = {

"AGUADILLA PR": "Aguadilla, Puerto Rico",
"ALBANY NY": "Albany, N.Y.",
"ALEXANDRIA LA": "Alexandria, La.",
"ALLENTOWN PA": "Allentown, Pa.",
"ANDROS": "Andros Island, The Bahamas",
"ANNAPOLIS MD": "Annapolis, Md.",
"ANTIGUA": "Antigua",
"APALACHICOLA": "Apalachicola, Fla.",
"ATLANTA GA": "Atlanta, Ga.",
"ATLANTIC CITY": "Atlantic City, N.J.",
"AUGUSTA GA": "Augusta, Ga.",
"AUGUSTA ME": "Augusta, Maine",
"AUSTIN TX": "Austin, Texas",
"BALD HEAD ISL": "Bald Head Island, N.C.",
"BALTIMORE MD": "Baltimore, Md.",
"BAR HARBOR ME": "Bar Harbor, Maine",
"BARBADOS": "Barbados",
"BARBUDA": "Barbuda",
"BATON ROUGE LA": "Baton Rouge, La.",
"BEAUFORT MCAS": "MCAS Beaufort, S.C.",
"BELIZE CITY": "Belize City, Belize",
"BELIZE": "Belize",
"BERMUDA": "Bermuda",
"BIRMINGHAM AL": "Birmingham, Ala.",
"BLUEFIELDS": "Bluefields, Nicaragua",
"BOSTON MA": "Boston, Mass.",
"BRIDGEPORT CT": "Bridgeport, Conn.",
"BROWNSVILLE TX": "Brownsville, Texas",
"BURAS LA": "Buras, La.",
"BURGEO NFLD": "Burgeo, Newfoundland",
"CAMAGUEY": "Camaguey, Cuba",
"CAMERON LA": "Cameron, La.",
"CAPE BEATA": "Cape Beata, Dominican Republic",
"CAPE HATTERAS": "Cape Hatteras, N.C.",
"CAPE HENLOPEN": "Cape Henlopen, Del.",
"CAPE RACE NFLD": "Cape Race, Newfoundland",
"CEDAR KEY FL": "Cedar Key, Fla.",
"CHARLESTON SC": "Charleston, S.C.",
"CHARLOTTE NC": "Charlotte, N.C.",
"CHARLOTTESVIL": "Charlottesville, Va.",
"CHERRY PT NC": "Cherry Point, N.C.",
"CIENFUEGOS": "Cienfuegos, Cuba",
"COCOA BEACH FL": "Cocoa Beach, Fla.",
"COLUMBIA SC": "Columbia, S.C.",
"COLUMBUS GA": "Columbus, Ga.",
"CONCORD NH": "Concord, N.H.",
"CORPUS CHRISTI": "Corpus Christi, Texas",
"COZUMEL MX": "Cozumel, Mexico",
"CP SAN ANTONIO": "badstuff", # This doesn't look like Texas
"CURACAO": "Cura‡ao",
"DANVILLE VA": "Danville, Va.",
"DAYTONA BEACH": "Daytona Beach, Fla.",
"DESTIN EXEC AP": "Destin, Fla.",
"DOMINICA": "Dominica",
"DOVER DE": "Dover, Del.",
"EASTPORT ME": "Eastport, Maine",
"EDDY POINT NS": "Eddy Point, Nova Scotia",
"ELIZABETH CTY": "Elizabeth City, N.C.",
"FAYETTEVILLE": "Fayetteville, N.C.",
"FLORENCE SC": "Florence, S.C.",
"FORT POLK LA": "Fort Polk, La.",
"FREEPORT TX": "Freeport, Texas",
"FRONTERA MX": "Frontera, Mexico",
"FT LAUDERDALE": "Fort Lauderdale, Fla.",
"FT MYERS FL": "Fort Myers, Fla.",
"FT PIERCE FL": "Fort Pierce, Fla.",
"GAINESVILLE FL": "Gainesville, Fla.",
"GALVESTON TX": "Galveston, Texas",
"GEORGETOWN SC": "Georgetown, S.C.",
"GFMX 250N 960W": "badstuff",
"GFMX 270N 960W": "badstuff",
"GFMX 280N 890W": "badstuff",
"GFMX 280N 910W": "badstuff",
"GFMX 280N 930W": "badstuff",
"GFMX 280N 950W": "badstuff",
"GFMX 290N 850W": "badstuff",
"GFMX 290N 870W": "badstuff",
"GONAIVES": "Gona‹ves, Haiti",
"GRAND BAHAMA": "Grand Bahama, The Bahamas",
"GRAND CAYMAN": "Grand Cayman Island",
"GRAND TURK": "Grand Turk Island, Turks and Caicos",
"GREAT EXUMA": "Great Exuma, The Bahamas",
"GREENSBORO NC": "Greensboro, N.C.",
"GRENADA": "Grenada",
"GUADELOUPE": "Guadeloupe",
"GUANAJA": "Guanaja, Honduras",
"GUANTANAMO BAY": "Guantanamo Bay, Cuba",
"GULFPORT MS": "Gulfport, Miss.",
"HALIFAX NS": "Halifax, Nova Scotia",
"HARLINGEN TX": "Harlingen, Texas",
"HARTFORD CT": "Hartford, Conn.",
"HAVANA": "Havana, Cuba",
"HIBERNIA OILFD": "Hibernia oilfield, 200 miles east of Canada",
"HIGH ISLAND TX": "High Island, Texas",
"HOMESTEAD ARB": "Homestead ARB, Fla.",
"HOUSTON TX": "Houston, Texas",
"HYANNIS MA": "Hyannis, Mass.",
"ILE ST PIERRE": "Ile Saint-Pierre, France",
"ISLE OF PINES": "Isla de la Juventud, Cuba",
"ISLIP NY": "Islip, N.Y.",
"JACKSON MS": "Jackson, Miss.",
"JACKSONVILLE": "Jacksonville, Fla.",
"JASPER TX": "Jasper, Texas",
"JUANGRIEGO": "Juan Griego, Venezuela",
"KEESLER AB": "Keesler AFB, Miss.",
"KEY WEST FL": "Key West, Fla.",
"KINGS BAY GA": "Kings Bay, Ga.",
"KINGSTON": "Kingston, Jamaica",
"KOUNTZE TX": "Kountze, Texas",
"LA PESCA MX": "La Pesca, Mexico",
"LAFAYETTE LA": "Lafayette, La.",
"LAKE CHARLES": "Lake Charles, La.",
"LES CAYES": "Les Cayes, Haiti",
"LIMON": "Lim¢n, Costa Rica",
"LITTLE RIVER": "Little River, S.C.",
"MARATHON FL": "Marathon, Fla.",
"MARCO ISLAND": "Marco Island, Fla.",
"MARTINIQUE": "Martinique",
"MATAGORDA TX": "Matagorda, Texas",
"MAYAGUANA": "Mayaguana, The Bahamas",
"MAYPORT NS FL": "Mayport Naval Station, Fla.",
"MAYPORT NS": "Naval Station Mayport, Fla.",
"MERIDA MX": "M‚rida, Mexico",
"MIAMI FL": "Miami, Fla.",
"MOBILE AL": "Mobile, Ala.",
"MONCTON NB": "Moncton, New Brunswick",
"MONTAUK POINT": "Montauk Point, N.Y.",
"MONTEGO BAY": "Montego Bay, Jamaica",
"MONTGOMERY AL": "Montgomery, Ala.",
"MOREHEAD CITY": "Morehead City, N.C.",
"MORGAN CITY LA": "Morgan City, La.",
"MYRTLE BEACH": "Myrtle Beach, S.C.",
"NANTUCKET MA": "Nantucket, Mass.",
"NAPLES FL": "Naples, Fla.",
"NEW HAVEN CT": "New Haven, Conn.",
"NEW IBERIA LA": "New Iberia, La.",
"NEW LONDON CT": "New London, Conn.",
"NEW ORLEANS LA": "New Orleans, La.",
"NEW PROVIDENCE": "New Providence, The Bahamas",
"NEW RIVER NC": "New River, N.C.",   # a.k.a. Jacksonville
"NEW YORK CITY": "New York City, N.Y.",
"NEWARK NJ": "Newark, N.J.",
"NORFOLK NAS": "Norfolk Naval Air Station",
"NORFOLK VA": "Norfolk, Va.",
"NWS EARLE NJ": "badstuff",
"NYC CNTRL PARK": "New York City, N.Y.",
"NYC JFK AIRPRT": "JFK Airport, N.Y.",
"OCEAN CITY MD": "Ocean City, Md.",
"OCEANA NAS VA": "Naval Air Station Oceana, Va.",
"ORLANDO FL": "Orlando, Fla.",
"PANAMA CITY FL": "Panama City, Fla.",
"PATRICK AFB": "Patrick AFB, Fla.",
"PAX RIVER NAS": "Patuxent River Naval Air Station, Md.",
"PENSACOLA FL": "Pensacola, Fla.",
"PENSACOLA NAS": "Pensacola NAS, Fla.",
"PHILADELPHIA": "Philadelphia, Pa.",
"PONCE PR": "Ponce, Puerto Rico",
"PONTA DELGADA": "Ponta Delgada, Azores".
"PORT-AU-PRINCE": "Port-Au-Prince, Haiti",
"PORT ARTHUR TX": "Port Arthur, Texas",
"PORT O CONNOR": "Port O'Connor, Texas",
"PORT OF SPAIN": "Port of Spain, Trinidad and Tobago", 
"PORTLAND ME": "Portland, Maine",
"PORTSMOUTH NH": "Portsmouth, N.H.",
"POUGHKEEPSIE": "Poughkeepsie, N.Y.",
"PROVIDENCE RI": "Providence, R.I.",
"PT GALLINAS": "Punta Gallinas, Colombia",
"PTX BASQUES": "badstuff",
"PUERTO BARRIOS": "Puerto Barrios, Guatemala",
"PUERTO CABEZAS": "Puerto Cabezas, Nicaragua",
"PUERTO PLATA": "Puerto Plata, Dominican Republic",
"RALEIGH NC": "Raleigh, N.C.",
"RICHMOND VA": "Richmond, Va.",
"ROCKPORT TX": "Rockport, Texas",
"ROCKY MT NC": "Rocky Mount, N.C.",
"SABA": "Saba, Leeward Islands",
"SABLE ISLAND": "Sable Island, Nova Scotia",
"SAINT CROIX": "Saint Croix, U.S. Virgin Islands",
"SAINT LUCIA": "Saint Lucia",
"SAINT MAARTEN": "Saint Maarten",    # A mix of Saint Martin and Sint Maartin?
"SAINT THOMAS": "Saint Thomas, U.S. Virgin Islands",
"SAN ANDRES": "San Andr‚s",
"SAN ANTONIO TX": "San Antonio, Texas",
"SAN JUAN PR": "San Juan, Puerto Rico",
"SAN JUAN": "San Juan, Puerto Rico",
"SAN SALVADOR": "San Salvador, The Bahamas",
"SANTA CRUZ AZO": "Santa Cruz das Flores, Azores",
"SANTO DOMINGO": "Santo Domingo, Dominican Republic",
"SAVANNAH GA": "Savannah, Ga.",
"SHREVEPORT LA": "Shreveport, La.",
"SPRINGFIELD MA": "Springfield, Mass.",
"ST EUSTATIUS": "St. Eustatius, Leeward Islands",
"ST JOHN NB": "St. John, New Brunswick",
"ST KITTS-NEVIS": "St. Kitts and Nevis, Leeward Islands",
"ST MARKS FL": "St. Marks, Fla.",
"STENNIS MS": "Stennis, Miss.",
"SURF CITY NC": "Surf City, N.C.",
"SYDNEY NS": "Sydney, Nova Scotia",
"TALLAHASSEE FL": "Tallahassee, Fla.",
"TAMPA FL": "Tampa, Fla.",
"TAMPICO MX": "Tampico, Mexico",
"THE VILLAGES": "The Villages, Fla.",
"TRENTON NJ": "Trenton, N.J.",
"TRINIDADTOBAGO": "Trinidad and Tobago",
"TUXPAN MX": "Tuxpan, Mexico",
"VENICE FL": "Venice, Fla.",
"VERACRUZ MX": "Veracruz, Mexico",
"VIEQUES PR": "Vieques, Puerto Rico",
"W PALM BEACH": "West Palm Beach, Fla.",
"WALLOPS CDA": "badstuff",
"WASHINGTON DC": "Washington, D.C.",
"WAYCROSS GA": "Waycross, Ga.",
"WHITING FLD FL": "NAS Whiting Field, Fla.",
"WILMINGTON NC": "Wilmington, N.C.",
"WORCESTER MA": "Worcester, Mass.",
"YARMOUTH NS": "Yarmouth, Nova Scotia",

	
"ZZZZZPLACEHOLDER": "badstuff"


}
