namedict = {

"WILMINGTON NC": "Wilmington, N.C.",
"BALD HEAD ISL": "Bald Head Island, N.C.",
"FLORENCE SC": "Florence, S.C.",
"COLUMBIA SC": "Columbia, S.C.",
"LITTLE RIVER": "Little River, S.C.",
"MYRTLE BEACH": "Myrtle Beach, S.C.",
"GEORGETOWN SC": "Georgetown, S.C.",
"CHARLESTON SC": "Charleston, S.C.",
"BEAUFORT MCAS": "MCAS Beaufort, S.C.",
"AUGUSTA GA": "Augusta, Ga.",
"SAVANNAH GA": "Savannah, Ga.",
"KINGS BAY GA": "Kings Bay, Ga.",
"WAYCROSS GA": "Waycross, Ga.",
"MAYPORT NS FL": "Mayport Naval Station, Fla.",
"JACKSONVILLE": "Jacksonville, Fla.",
"GAINESVILLE FL": "Gainesville, Fla.",
"DAYTONA BEACH": "Daytona Beach, Fla.",
"THE VILLAGES": "The Villages, Fla.",
"ORLANDO FL": "Orlando, Fla.",
"COCOA BEACH FL": "Cocoa Beach, Fla.",
"PATRICK AFB": "Patrick AFB, Fla.",
"FT PIERCE FL": "Fort Pierce, Fla.",
"W PALM BEACH": "West Palm Beach, Fla.",
"FT LAUDERDALE": "Fort Lauderdale, Fla.",
"MIAMI FL": "Miami, Fla.",
"HOMESTEAD ARB": "Homestead ARB, Fla.",
"MARATHON FL": "Marathon, Fla.",
"KEY WEST FL": "Key West, Fla.",
"NAPLES FL": "Naples, Fla.",
"FT MYERS FL": "Fort Myers, Fla.",
"VENICE FL": "Venice, Fla.",
"TAMPA FL": "Tampa, Fla.",
"CEDAR KEY FL": "Cedar Key, Fla.",
"TALLAHASSEE FL": "Tallahassee, Fla.",
"ST MARKS FL": "St. Marks, Fla.",
"APALACHICOLA": "Apalachicola, Fla.",
"GFMX 290N 850W": "badstuff",
"PANAMA CITY FL": "Panama City, Fla.",
"DESTIN EXEC AP": "Destin, Fla.",
"COLUMBUS GA": "Columbus, Ga.",
"WHITING FLD FL": "NAS Whiting Field, Fla.",
"PENSACOLA FL": "Pensacola, Fla.",
"GFMX 290N 870W": "badstuff",
"GRAND BAHAMA": "Grand Bahama, The Bahamas",
"NEW PROVIDENCE": "New Providence, The Bahamas",
"ANDROS": "Andros Island, The Bahamas",
"GREAT EXUMA": "Great Exuma, The Bahamas",
"SAN SALVADOR": "San Salvador, The Bahamas",
"MAYAGUANA": "Mayaguana, The Bahamas",
"GRAND TURK": "Grand Turk Island, Turks and Caicos",
"HAVANA": "Havana, Cuba",
"PUERTO PLATA": "Puerto Plata, Dominican Republic",
"SAN JUAN PR": "San Juan, Puerto Rico",
"VIEQUES PR": "Vieques, Puerto Rico",
"SAINT THOMAS": "Saint Thomas, U.S. Virgin Islands",
"SAINT CROIX": "Saint Croix, U.S. Virgin Islands",
"ATLANTA GA": "Atlanta, Ga.",
"MONTGOMERY AL": "Montgomery, Ala.",
"MOBILE AL": "Mobile, Ala.",
"GULFPORT MS": "Gulfport, Miss.",
"GFMX 280N 890W": "badstuff",
"ISLE OF PINES": "Isla de la Juventud, Cuba",
"CIENFUEGOS": "Cienfuegos, Cuba",
"FAYETTEVILLE": "Fayetteville, N.C.",
"ROCKY MT NC": "Rocky Mount, N.C.",
"OCEANA NAS VA": "Naval Air Station Oceana, Va.",
"RICHMOND VA": "Richmond, Va.",
"MOREHEAD CITY": "Morehead City, N.C.",
"SURF CITY NC": "Surf City, N.C.",
"WALLOPS CDA": "badstuff",
"NORFOLK NAS": "Norfolk Naval Air Station",
"NEW RIVER NC": "New River, N.C.",   # a.k.a. Jacksonville
"DANVILLE VA": "Danville, Va.",
"CHERRY PT NC": "Cherry Point, N.C.",
"RALEIGH NC": "Raleigh, N.C.",
"CAPE HATTERAS": "Cape Hatteras, N.C.",
"CHARLOTTESVIL": "Charlottesville, Va.",
"PAX RIVER NAS": "Patuxent River Naval Air Station, Md.",
"NORFOLK VA": "Norfolk, Va.",
"GREENSBORO NC": "Greensboro, N.C.",
"OCEAN CITY MD": "Ocean City, Md.",
"CAPE HENLOPEN": "Cape Henlopen, Del.",
"ELIZABETH CTY": "Elizabeth City, N.C.",
"CHARLOTTE NC": "Charlotte, N.C.",
"WASHINGTON DC": "Washington, D.C.",
"NYC JFK AIRPRT": "JFK Airport, N.Y.",
"BRIDGEPORT CT": "Bridgeport, Conn.",
"PHILADELPHIA": "Philadelphia, Pa.",
"POUGHKEEPSIE": "Poughkeepsie, N.Y.",
"TRENTON NJ": "Trenton, N.J.",
"ISLIP NY": "Islip, N.Y.",
"NANTUCKET MA": "Nantucket, Mass.",
"PROVIDENCE RI": "Providence, R.I.",
"MONTAUK POINT": "Montauk Point, N.Y.",
"NEW LONDON CT": "New London, Conn.",
"HYANNIS MA": "Hyannis, Mass.",
"HARTFORD CT": "Hartford, Conn.",
"BALTIMORE MD": "Baltimore, Md.",
"ALLENTOWN PA": "Allentown, Pa.",
"NWS EARLE NJ": "badstuff",
"ATLANTIC CITY": "Atlantic City, N.J.",
"SPRINGFIELD MA": "Springfield, Mass.",
"NEWARK NJ": "Newark, N.J.",
"NEW HAVEN CT": "New Haven, Conn.",
"DOVER DE": "Dover, Del.",
"ANNAPOLIS MD": "Annapolis, Md.",
"NYC CNTRL PARK": "New York City, N.Y.",
"BOSTON MA": "Boston, Mass.",
"WORCESTER MA": "Worcester, Mass.",
"PORTLAND ME": "Portland, Maine",
"ALBANY NY": "Albany, N.Y.",
"CONCORD NH": "Concord, N.H.",
"PORTSMOUTH NH": "Portsmouth, N.H.",
"YARMOUTH NS": "Yarmouth, Nova Scotia",
"HALIFAX NS": "Halifax, Nova Scotia",
"AUGUSTA ME": "Augusta, Maine",
"EASTPORT ME": "Eastport, Maine",
"ST JOHN NB": "St. John, New Brunswick",
"SABLE ISLAND": "Sable Island, Nova Scotia",
"BAR HARBOR ME": "Bar Harbor, Maine",
"ILE ST PIERRE": "Ile Saint-Pierre, France",
"SYDNEY NS": "Sydney, Nova Scotia",
"PTX BASQUES": "badstuff",
"MONCTON NB": "Moncton, New Brunswick",
"BURGEO NFLD": "Burgeo, Newfoundland",
"EDDY POINT NS": "Eddy Point, Nova Scotia",
"CAPE RACE NFLD": "Cape Race, Newfoundland",
"HIBERNIA OILFD": "Hibernia oilfield, 200 miles east of Canada"

}
