namedict = {

"WILMINGTON NC": "Wilmington, N.C.",
"BALD HEAD ISL": "Bald Head Island, N.C.",
"FLORENCE SC": "Florence, S.C.",
"COLUMBIA SC": "Columbia, S.C.",
"LITTLE RIVER": "Little River, S.C.",
"MYRTLE BEACH": "Myrtle Beach, S.C.",
"GEORGETOWN SC": "Georgetown, S.C.",
"CHARLESTON SC": "Charleston, S.C.",
"BEAUFORT MCAS": "MCAS Beaufort, S.C.",
"AUGUSTA GA": "Augusta, Ga.",
"SAVANNAH GA": "Savannah, Ga.",
"KINGS BAY GA": "Kings Bay, Ga.",
"WAYCROSS GA": "Waycross, Ga.",
"MAYPORT NS FL": "Mayport Naval Station, Fla.",
"JACKSONVILLE": "Jacksonville, Fla.",
"GAINESVILLE FL": "Gainesville, Fla.",
"DAYTONA BEACH": "Daytona Beach, Fla.",
"THE VILLAGES": "The Villages, Fla.",
"ORLANDO FL": "Orlando, Fla.",
"COCOA BEACH FL": "Cocoa Beach, Fla.",
"PATRICK AFB": "Patrick AFB, Fla.",
"FT PIERCE FL": "Fort Pierce, Fla.",
"W PALM BEACH": "West Palm Beach, Fla.",
"FT LAUDERDALE": "Fort Lauderdale, Fla.",
"MIAMI FL": "Miami, Fla.",
"HOMESTEAD ARB": "Homestead ARB, Fla.",
"MARATHON FL": "Marathon, Fla.",
"KEY WEST FL": "Key West, Fla.",
"NAPLES FL": "Naples, Fla.",
"FT MYERS FL": "Fort Myers, Fla.",
"VENICE FL": "Venice, Fla.",
"TAMPA FL": "Tampa, Fla.",
"CEDAR KEY FL": "Cedar Key, Fla.",
"TALLAHASSEE FL": "Tallahassee, Fla.",
"ST MARKS FL": "St. Marks, Fla.",
"APALACHICOLA": "Apalachicola, Fla.",
"GFMX 290N 850W": "badstuff",
"PANAMA CITY FL": "Panama City, Fla.",
"DESTIN EXEC AP": "Destin, Fla.",
"COLUMBUS GA": "Columbus, Ga.",
"WHITING FLD FL": "NAS Whiting Field, Fla.",
"PENSACOLA FL": "Pensacola, Fla.",
"GFMX 290N 870W": "badstuff",
"GRAND BAHAMA": "Grand Bahama, The Bahamas",
"NEW PROVIDENCE": "New Providence, The Bahamas",
"ANDROS": "Andros Island, The Bahamas",
"GREAT EXUMA": "Great Exuma, The Bahamas",
"SAN SALVADOR": "San Salvador, The Bahamas",
"MAYAGUANA": "Mayaguana, The Bahamas",
"GRAND TURK": "Grand Turk Island, Turks and Caicos",
"HAVANA": "Havana, Cuba",
"PUERTO PLATA": "Puerto Plata, Dominican Republic",
"SAN JUAN PR": "San Juan, Puerto Rico",
"VIEQUES PR": "Vieques, Puerto Rico",
"SAINT THOMAS": "Saint Thomas, U.S. Virgin Islands",
"SAINT CROIX": "Saint Croix, U.S. Virgin Islands",
"ATLANTA GA": "Atlanta, Ga.",
"MONTGOMERY AL": "Montgomery, Ala.",
"MOBILE AL": "Mobile, Ala.",
"GULFPORT MS": "Gulfport, Miss.",
"GFMX 280N 890W": "badstuff",
"ISLE OF PINES": "Isla de la Juventud, Cuba",
"CIENFUEGOS": "Cienfuegos, Cuba",
"FAYETTEVILLE": "Fayetteville, N.C.",
"ROCKY MT NC": "Rocky Mount, N.C.",
"OCEANA NAS VA": "Naval Air Station Oceana, Va.",
"RICHMOND VA": "Richmond, Va.",
"MOREHEAD CITY": "Morehead City, N.C.",
"SURF CITY NC": "Surf City, N.C.",
"WALLOPS CDA": "badstuff",
"NORFOLK NAS": "Norfolk Naval Air Station",
"NEW RIVER NC": "New River, N.C.",   # a.k.a. Jacksonville
"DANVILLE VA": "Danville, Va.",
"CHERRY PT NC": "Cherry Point, N.C.",
"RALEIGH NC": "Raleigh, N.C.",
"CAPE HATTERAS": "Cape Hatteras, N.C.",
"CHARLOTTESVIL": "Charlottesville, Va.",
"PAX RIVER NAS": "Patuxent River Naval Air Station, Md.",
"NORFOLK VA": "Norfolk, Va.",
"GREENSBORO NC": "Greensboro, N.C.",
"OCEAN CITY MD": "Ocean City, Md.",
"CAPE HENLOPEN": "Cape Henlopen, Del.",
"ELIZABETH CTY": "Elizabeth City, N.C.",
"CHARLOTTE NC": "Charlotte, N.C.",
"WASHINGTON DC": "Washington, D.C.",
"NYC JFK AIRPRT": "JFK Airport, N.Y.",
"BRIDGEPORT CT": "Bridgeport, Conn.",
"PHILADELPHIA": "Philadelphia, Pa.",
"POUGHKEEPSIE": "Poughkeepsie, N.Y.",
"TRENTON NJ": "Trenton, N.J.",
"ISLIP NY": "Islip, N.Y.",
"NANTUCKET MA": "Nantucket, Mass.",
"PROVIDENCE RI": "Providence, R.I.",
"MONTAUK POINT": "Montauk Point, N.Y.",
"NEW LONDON CT": "New London, Conn.",
"HYANNIS MA": "Hyannis, Mass.",
"HARTFORD CT": "Hartford, Conn.",
"BALTIMORE MD": "Baltimore, Md.",
"ALLENTOWN PA": "Allentown, Pa.",
"NWS EARLE NJ": "badstuff",
"ATLANTIC CITY": "Atlantic City, N.J.",
"SPRINGFIELD MA": "Springfield, Mass.",
"NEWARK NJ": "Newark, N.J.",
"NEW HAVEN CT": "New Haven, Conn.",
"DOVER DE": "Dover, Del.",
"ANNAPOLIS MD": "Annapolis, Md.",
"NYC CNTRL PARK": "New York City, N.Y.",
"BOSTON MA": "Boston, Mass.",
"WORCESTER MA": "Worcester, Mass.",
"PORTLAND ME": "Portland, Maine",
"ALBANY NY": "Albany, N.Y.",
"CONCORD NH": "Concord, N.H.",
"PORTSMOUTH NH": "Portsmouth, N.H.",
"YARMOUTH NS": "Yarmouth, Nova Scotia",
"HALIFAX NS": "Halifax, Nova Scotia",
"AUGUSTA ME": "Augusta, Maine",
"EASTPORT ME": "Eastport, Maine",
"ST JOHN NB": "St. John, New Brunswick",
"SABLE ISLAND": "Sable Island, Nova Scotia",
"BAR HARBOR ME": "Bar Harbor, Maine",
"ILE ST PIERRE": "Ile Saint-Pierre, France",
"SYDNEY NS": "Sydney, Nova Scotia",
"PTX BASQUES": "badstuff",
"MONCTON NB": "Moncton, New Brunswick",
"BURGEO NFLD": "Burgeo, Newfoundland",
"EDDY POINT NS": "Eddy Point, Nova Scotia",
"CAPE RACE NFLD": "Cape Race, Newfoundland",
"HIBERNIA OILFD": "Hibernia oilfield, 200 miles east of Canada",
"GFMX 280N 910W": "badstuff",
"BERMUDA": "Bermuda",
"BURAS LA": "Buras, La.",
"FREEPORT TX": "Freeport, Texas",
"MORGAN CITY LA": "Morgan City, La.",
"PENSACOLA NAS": "Pensacola NAS, Fla.",
"HIGH ISLAND TX": "High Island, Texas",
"GFMX 270N 960W": "badstuff",
"FRONTERA MX": "Frontera, Mexico",
"SHREVEPORT LA": "Shreveport, La.",
"ALEXANDRIA LA": "Alexandria, La.",
"GFMX 280N 930W": "badstuff",
"MERIDA MX": "Mérida, Mexico",
"CAMERON LA": "Cameron, La.",
"NEW ORLEANS LA": "New Orleans, La.",
"MATAGORDA TX": "Matagorda, Texas",
"LAFAYETTE LA": "Lafayette, La.",
"JACKSON MS": "Jackson, Miss.",
"PORT O CONNOR": "Port O'Connor, Texas",
"HOUSTON TX": "Houston, Texas",
"KEESLER AB": "Keesler AFB, Miss.",
"NEW IBERIA LA": "New Iberia, La.",
"BATON ROUGE LA": "Baton Rouge, La.",
"JASPER TX": "Jasper, Texas",
"LAKE CHARLES": "Lake Charles, La.",
"STENNIS MS": "Stennis, Miss.",
"FORT POLK LA": "Fort Polk, La.",
"GALVESTON TX": "Galveston, Texas",
"PORT ARTHUR TX": "Port Arthur, Texas",
"KOUNTZE TX": "Kountze, Texas",
"GFMX 280N 950W": "badstuff",
"AUSTIN TX": "Austin, Texas",
"CORPUS CHRISTI": "Corpus Christi, Texas",
"BELIZE CITY": "Belize City, Belize",
"GFMX 250N 960W": "badstuff",
"COZUMEL MX": "Cozumel, Mexico",
"ROCKPORT TX": "Rockport, Texas",
"BIRMINGHAM AL": "Birmingham, Ala.",
"CP SAN ANTONIO": "badstuff", # This doesn't look like Texas
"PONCE PR": "Ponce, Puerto Rico",
"SANTO DOMINGO": "Santo Domingo, Dominican Republic",
"SABA": "Saba, Leeward Islands",
"ST EUSTATIUS": "St. Eustatius, Leeward Islands",
"GUANTANAMO BAY": "Guantanamo Bay, Cuba",
"AGUADILLA PR": "Aguadilla, Puerto Rico",
"ST KITTS-NEVIS": "St. Kitts and Nevis, Leeward Islands",
"PORT-AU-PRINCE": "Port-Au-Prince, Haiti",
"SAINT MAARTEN": "Saint Maarten",    # A mix of Saint Martin and Sint Maartin?
"CAPE BEATA": "Cape Beata, Dominican Republic",
"CAMAGUEY": "Camaguey, Cuba",
"ANTIGUA": "Antigua",
"BARBUDA": "Barbuda",
"MONTEGO BAY": "Montego Bay, Jamaica",
"KINGSTON": "Kingston, Jamaica",
"LES CAYES": "Les Cayes, Haiti",
"SAN ANTONIO TX": "San Antonio, Texas",
"GRAND CAYMAN": "Grand Cayman Island",
"BROWNSVILLE TX": "Brownsville, Texas",
"HARLINGEN TX": "Harlingen, Texas",
"PUERTO BARRIOS": "Puerto Barrios, Guatemala",
"PUERTO CABEZAS": "Puerto Cabezas, Nicaragua",
"BLUEFIELDS": "Bluefields, Nicaragua",
"SAN ANDRES": "San Andrés",
"LIMON": "Limón, Costa Rica",
"GUANAJA": "Guanaja, Honduras",
"BARBADOS": "Barbados",
"BELIZE": "Belize",
"CURACAO": "Curaçao",
"DOMINICA": "Dominica",
"GONAIVES": "Gonaïves, Haiti",
"GRENADA": "Grenada",
"GUADELOUPE": "Guadeloupe",
"JUANGRIEGO": "Juan Griego, Venezuela",
"LA PESCA MX": "La Pesca, Mexico",
"MARCO ISLAND": "Marco Island, Fla.",
"MARTINIQUE": "Martinique",
"MAYPORT NS": "Naval Station Mayport, Fla.",
"NEW YORK CITY": "New York City, N.Y.",
"PONTA DELGADA": "Ponta Delgada, Azores",
"PORT OF SPAIN": "Port of Spain, Trinidad and Tobago", 
"PT GALLINAS": "Punta Gallinas, Colombia",
"SAINT LUCIA": "Saint Lucia",
"SAN JUAN": "San Juan, Puerto Rico",
"SANTA CRUZ AZO": "Santa Cruz das Flores, Azores",
"TAMPICO MX": "Tampico, Mexico",
"TRINIDADTOBAGO": "Trinidad and Tobago",
"TUXPAN MX": "Tuxpan, Mexico",
"AVES": "Isla de Aves, Venezuela",
"SAINT VINCENT": "St. Vincent",
"VERACRUZ MX": "Veracruz, Mexico",
"ISLA SOCORRO": "Socorro Island, Mexico",
"P PENASCO": "Puerto Peñasco, Mexico",
"P ABREOJOS": "Punta Abreojos, Mexico",
"GUAYMAS": "Guaymas, Mexico",
"25N 120W": "badstuff",
"SAN DIEGO CA": "San Diego, Calif.",
"IS GUADALUPE": "Guadalupe Island, Mexico",
"20N 110W": "badstuff",
"BAHIA KINO": "Bahía Kino, Mexico",
"LORETO": "Loreto, Zacatecas, Mexico",
"S CATALINA IS": "South Catalina Island, Calif.",
"TIJUANA": "Tijuana, Mexico",
"LA PAZ": "La Paz, Baja California Sur, Mexico",
"SAN JOSE CABO": "San José del Cabo, Baja California Sur, Mexico",
"HUATABAMPO": "Huatabampo, Sonora, Mexico",
"25N 115W": "badstuff",
"CABO SAN LUCAS": "Cabo San Lucas, Baja California Sur, Mexico",
"SANTA CRUZ IS": "Santa Cruz Island, Calif.",
"OXNARD CA": "Oxnard, Calif.",
"30N 120W": "badstuff",
"HERMOSILLO": "Hermosillo, Sonora, Mexico",
"ISLA CLARION": "Clarion Island, Mexico",
"ENSENADA": "Ensenada, Baja California, Mexico",
"20N 115W": "badstuff",
"YUMA AZ": "Yuma, Ariz.",
"LONG BEACH/LA": "Long Beach and Los Angeles, Calif.",
"PUNTA EUGENIA": "Punta Eugenia, Baja California Sur, Mexico",
"...THERE IS NO": "badstuff",
"10N 100W": "badstuff",
"10N 105W": "badstuff",
"10N 110W": "badstuff",
"10N 115W": "badstuff",
"10N 120W": "badstuff",
"10N 125W": "badstuff",
"10N 130W": "badstuff",
"10N 135W": "badtsuff",
"10N 140W": "badstuff",
"10N 145W": "badstuff",
"10N 150W": "badstuff",
"10N 160W": "badstuff",
"10N 165W": "badstuff",
"10N 170W": "badstuff",
"10N 175W": "badstuff",
"10N 90W": "badstuff",
"10N 95W": "badstuff",
"15N 100W": "badstuff",
"15N 105W": "badstuff",
"15N 110W": "badstuff",
"15N 115W": "badstuff",
"15N 120W": "badstuff",
"15N 125W": "badstuff",
"15N 130W": "badstuff",
"15N 135W": "badstuff",
"15N 140W": "badstuff",
"15N 145W": "badstuff",
"15N 150W": "badstuff",
"15N 155W": "badstuff",
"15N 160W": "badstuff",
"15N 165W": "badstuff",
"15N 170W": "badstuff",
"15N 175W": "badstuff",
"15N 95W": "badstuff",
"18N 156W": "badstuff",
"20N 120W": "badstuff",
"20N 125W": "badstuff",
"20N 130W": "badstuff",
"20N 135W": "badstuff",
"20N 140W": "badstuff",
"20N 145W": "badstuff",
"20N 150W": "badstuff",
"20N 151W": "badstuff",
"20N 154W": "badstuff",
"20N 160W": "badstuff",
"20N 165W": "badstuff",
"20N 170W": "badstuff",
"20N 175W": "badstuff",
"21N 156W": "badstuff",
"21N 158W": "badstuff",
"21N 160W": "badstuff",
"22N 164W": "badstuff",
"25N 125W": "badstuff",
"25N 130W": "badstuff",
"25N 135W": "badstuff",
"25N 140W": "badstuff",
"25N 145W": "badstuff",
"25N 150W": "badstuff",
"25N 160W": "badstuff",
"25N 165W": "badstuff",
"25N 170W": "badstuff",
"25N 175W": "badstuff",
"26N 159W": "badstuff",
"30N 125W": "badstuff",
"30N 130W": "badstuff",
"30N 135W": "badstuff",
"30N 140W": "badstuff",
"30N 145W": "badstuff",
"30N 150W": "badstuff",
"30N 160W": "badstuff",
"30N 165W": "badstuff",
"30N 170W": "badstuff",
"30N 175W": "badstuff",
"35N 150W": "badstuff",
"35N 160W": "badstuff",
"35N 165W": "badstuff",
"35N 170W": "badstuff",
"35N 175W": "badstuff",
"40N 150W": "badstuff",
"40N 160W": "badstuff",
"40N 165W": "badstuff",
"ACAPULCO": "Acapulco, Mexico",
"AMAPALA": "Amapala, Tiger Island, Honduras",
"AND THEREFORE": "badstuff",
"BARKING SANDS": "Barking Sands Beach, Kauai, Hawaii",
"BARRA NAVIDAD": "Barra de Navidad, Jalisco, Mexico",
"BRADSHAW AAF": "Bradshaw Army Airfield, Hawaii",
"BUOY 51002": "badstuff",
"BUOY 51003": "badstuff",
"BUOY 51004": "badstuff",
"BUOY 51101": "badstuff",
"CHOLUTECA": "Choluteca, Honduras",
"CLIPPERTON IS": "Clipperton Island",
"CULIACAN": "Culiacán, Sinaloa, Mexico",
"FR FRIG SHOALS": "French Frigate Shoals",
"GARDNER PINN": "Gardner Pinnacles",
"GUATEMALA CITY": "Guatemala City",
"HANA": "Hana, Maui, Hawaii",
"HILO": "Hilo, Hawaii",
"HONOLULU": "Honolulu",
"HOUMA LA": "Houma, La.",
"HUATULCO": "Huatulco, Oaxaca, Mexico",
"ISLAS MARIAS": "Islas Marías, Mexico",
"JOHNSTON ISL": "Johnston Atoll",
"JOINT BASE PHH": "Joint Base Pearl Harbor-Hickam",
"KAHULUI": "Kahului, Maui, Hawaii",
"KAILUA-KONA": "Kailua-Kona, Hawaii",
"KAUNAKAKAI": "Kaunakakai, Molokai, Hawaii",
"KURE": "Kure Atoll",
"LANAI CITY": "Lāna‘i City, Maui, Hawaii",
"LAYSAN": "Laysan",
"LIHUE": "Lihue, Kauai, Hawaii",
"LISIANSKI": "Lisianski Island",
"LOS MOCHIS": "Los Mochis, Sinaloa, Mexico",
"MANAGUA": "Managua, Nicaragua",
"MARO REEF": "Maro Reef",
"MAZATLAN": "Mazatlán, Sinaloa, Mexico",
"MCALLEN TX": "McAllen, Texas",
"MIDWAY": "Midway Island",
"NECKER": "Necker Island",
"NIHOA": "Nihoa",
"NIIHAU": "Niʻihau",
"P ANGEL": "Puerto Ángel, Oaxaca, Mexico",
"P SAN JOSE": "Puerto San José, Guatemala",
"P VALLARTA": "Puerto Vallarta, Jalisco, Mexico",
"PEARL/HERMES": "Pearl and Hermes Atoll",
"PONCE": "Ponce, Puerto Rico",
"PUERTO CUTUCO": "Puerto Cutuco, El Salvador",
"RIBIERA GRANDE": "Ribeira Grande, Azores",
"S SALVADOR": "San Salvador, El Salvador",
"TAPACHULA": "Tapachula, Chiapas, Mexico",
"TEGUCIGALPA": "Tegucigalpa, Honduras",
"ZIHUATANEJO": "Zihuatanejo, Guerrero, Mexico",
	
"ZZZZZPLACEHOLDER": "badstuff"


}
